version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
    ports:
      - "80:5000"
    environment:
      - USE_RDS=true
      - RDS_HOST=flask-app.c6benyjuoknd.us-east-1.rds.amazonaws.com
      - RDS_DATABASE=flask_app
      - RDS_USER=root
      - RDS_PASSWORD=Shahid#123
# simple service to test RDS connection
  test-rds:
    image: mysql:5.7
    environment:
      - MYSQL_HOST=flask-app.c6benyjuoknd.us-east-1.rds.amazonaws.com
      - MYSQL_DATABASE=flask_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Shahid#123
